# Generated by Django 4.2.7 on 2025-07-15 10:21

import blog.models
import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="banner_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for banner image (accessibility)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Feature this post on homepage"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO meta description (max 160 characters)",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="meta_keywords",
            field=models.CharField(
                blank=True, help_text="SEO keywords, comma-separated", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image for the blog post",
                null=True,
                upload_to=blog.models.blog_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text="Main blog content with rich text formatting"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="description",
            field=models.TextField(
                help_text="Brief description for SEO and previews (50-500 characters)",
                validators=[
                    django.core.validators.MinLengthValidator(50),
                    django.core.validators.MaxLengthValidator(500),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(
                help_text="Blog post title (5-200 characters)",
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
