services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_backend.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.vercel.app"

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: free
