# Generated by Django 4.2.7 on 2025-07-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "detailed_description",
                    models.TextField(
                        blank=True,
                        help_text="Longer description for project detail page",
                    ),
                ),
                (
                    "features",
                    models.JSONField(default=list, help_text="List of key features"),
                ),
                ("github_link", models.URLField(blank=True, null=True)),
                ("live_link", models.URLField(blank=True, null=True)),
                ("image", models.URLField(help_text="Main project image URL")),
                (
                    "gallery_images",
                    models.JSONField(
                        default=list, help_text="Additional project images"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("planned", "Planned"),
                            ("archived", "Archived"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.CharField(
                        blank=True, help_text="Client or company name", max_length=100
                    ),
                ),
                ("team_size", models.PositiveIntegerField(default=1)),
                (
                    "my_role",
                    models.CharField(
                        blank=True, help_text="Your role in the project", max_length=100
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        blank=True, help_text="Technical challenges faced"
                    ),
                ),
                (
                    "solutions",
                    models.TextField(blank=True, help_text="Solutions implemented"),
                ),
                ("lessons_learned", models.TextField(blank=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("database", "Database"),
                            ("tools", "Tools"),
                            ("cloud", "Cloud"),
                            ("mobile", "Mobile"),
                            ("devops", "DevOps"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="CSS class for icon (e.g., 'fab fa-python')",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10B981", help_text="Hex color code", max_length=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_position", models.CharField(max_length=100)),
                ("client_company", models.CharField(max_length=100)),
                ("client_avatar", models.URLField(blank=True, null=True)),
                ("testimonial", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="Rating out of 5"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.ManyToManyField(blank=True, to="projects.techstack"),
        ),
    ]
