# Generated by Django 4.2.7 on 2025-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("award", "Award"),
                            ("certification", "Certification"),
                            ("milestone", "Milestone"),
                            ("recognition", "Recognition"),
                            ("publication", "Publication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_achieved", models.DateField()),
                ("issuing_organization", models.CharField(blank=True, max_length=100)),
                ("certificate_url", models.URLField(blank=True, null=True)),
                ("badge_image", models.URLField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "-date_achieved"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Maath Mphepo Portfolio", max_length=100),
                ),
                (
                    "site_description",
                    models.TextField(default="Backend Developer & Software Engineer"),
                ),
                ("site_keywords", models.TextField(blank=True)),
                (
                    "site_author",
                    models.CharField(default="Maath Mphepo", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(default="maath@example.com", max_length=254),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("google_tag_manager_id", models.CharField(blank=True, max_length=50)),
                ("blog_enabled", models.BooleanField(default=True)),
                ("projects_enabled", models.BooleanField(default=True)),
                ("contact_form_enabled", models.BooleanField(default=True)),
                ("newsletter_enabled", models.BooleanField(default=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("avatar", models.URLField(blank=True, null=True)),
                ("testimonial", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="Rating out of 5"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
