# Generated by Django 4.2.7 on 2025-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True, null=True)),
                ("budget_range", models.CharField(blank=True, max_length=50)),
                ("project_timeline", models.CharField(blank=True, max_length=100)),
                (
                    "how_found",
                    models.CharField(
                        blank=True, help_text="How they found you", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes"),
                ),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where they subscribed from",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                            ("medium", "Medium"),
                            ("dev", "Dev.to"),
                            ("stackoverflow", "Stack Overflow"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("username", models.CharField(blank=True, max_length=100)),
                (
                    "icon_class",
                    models.CharField(help_text="CSS class for icon", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "platform"],
            },
        ),
    ]
